export const ERRORS = {
	NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
	INCORRECT_PASS: 'INCORRECT_PASSWORD',
	ID_UNDEFINED: 'ID_UNDEFINED',
	NOT_FOUND: 'ENTITY_NOT_FOUND',
	NOT_CREATOR: 'NOT_CREATOR',
	USER: {
		EXIST: 'USER_EXIST',
		NOT_EXIST: 'USER_NOT_EXIST',
	},
};

export const MESSAGES = {
	USER: {
		LOGINED: 'USER_LOGINED',
		EMAIL_SENDED: 'EMAIL_SENDED',
		PASSWORD_CHANGED: 'PASSWORD_CHANGED',
		CREATED: 'USER_CREATED',
		ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',
	},

	TODO: {
		CREATED: 'TODO_CREATED',
		UPDATED: 'TODO_UPDATED',
		DELETED: 'TODO_DELETED',
	},
};
